source "https://rubygems.org"

ruby ">= 3.0"
gem "rails"
gem "sqlite3"
gem "puma"
gem "tzinfo-data", platforms: %i[windows jruby]

gem "oj_serializers"
gem "alba"
gem "active_model_serializers"

gem "typelizer", path: "../.."

gem "rspec-rails"
